#!/bin/bash

#Check GPG Key End Date

DIR=/opt/services/dodoc_workflow/GRDF/PGP-Encrypt-Decrypt

function run() {

                RESULT=$(gpg --with-colons $1 | grep -v pub | awk '{print $3}' | cut -f1 -d "]" | sed s/\-//g)
}

for i in $(ls $DIR/*.asc)
do
        run $i
done


EXPIRATION=$(echo $(expr '(' $(date -d $RESULT  +%s) - $(date +%s) + 86399 ')' / 86400))


if [ $EXPIRATION -le 31 ]; then
        echo $EXPIRATION
else
        echo "1"
fi
