#!/bin/bash

 

fsTmpFull=`df -h | grep "/tmp" |awk '{print $5}' |grep 100`                                                                    # Check de l'espace /tmp et vérification

if [ $? = 0 ]; then

  echo "Action impossible, le /tmp est full."

  exit 2

fi

 

touch /tmp/mount_failed                                                                                                                                                                            

su -l root -c "mount -a 2> /tmp/mount_failed 1>/dev/null"                                                                    # écrire le stderr dans mount_failed

 

count=`cat /tmp/mount_failed | wc -m`

if [ "$count" = 0 ]; then                                                                                                                                                                                                 # Vérification si erreur fstab

  echo "Pas de probleme dans la FSTAB"

else

  echo "Probleme dans la FSTAB"

  exit 2

fi

 

rm -f /tmp/mount_failed                                                                                                                                                                                                                            # suppression du fichier temporaire

exit 0
