#!/bin/bash
date >> /var/log/restart_jboss.log
echo "Extinction du jboss" | tee -a /var/log/restart_jboss.log

/etc/init.d/jbossas stop >> /var/log/restart_jboss.log

echo "Attente de 2 min, le temps que le jboss s'éteigne"

sleep 120 #attente 2min le temps de l'arret du jboss

#récupération des pid des processus jboss restant
JBOSS=$(ps -u jboss| grep java | awk  ' {print $1}')

#récupération de l'erreur en cas de kill
trap kill ERR

#kill les processus ne s'étant pas arrete au bout de 2min
for element in $JBOSS
do
        kill -9 $element
        echo "kill $element" >> /var/log/restart_jboss.log
done

/etc/init.d/jbossas start >> /var/log/restart_jboss.log

echo "Redémarrage du jboss en cours, attente de 2 min le temps du redémarrage"
sleep 120 # attente 2min le demarrage

jboss_web=$(ps -f -u  jboss | grep java | grep web-prod)
jboss_ut=$(ps -f -u  jboss | grep java | grep ut-prod)
jboss_ws=$(ps -f -u  jboss | grep java | grep ws-prod)
#jboss_sched=$(ps -f -u jboss | grep java | grep sched-prod) #A décommenter sur les jboss qui possèdent un scheduler

if [ ! jboss_web ] || [ ! jboss_ut ] || [ ! jboss_ws ] #|| [ ! jboss_sched ] #A décommenter sur les jboss qui possèdent un scheduler
then
        echo -e "Subject:Erreur de redemarrage du JBoss.\n\nBonjour\n\nLe JBoss a rencontré un soucis de redémarrage, merci de vérifier les services,\n\nCordialement." | /usr/sbin/sendmail systeme-si@dataone.fr

        echo "Fin du redémarrage des jboss en erreur" | tee -a /var/log/restart_jboss.log
        date >> /var/log/restart_jboss.log
        echo "" >> /var/log/restart_jboss.log
else
        echo -e "Subject:Redemarrage du JBoss.\n\nBonjour\n\nLe JBoss a redémarré avec succès,\n\nCordialement." | /usr/sbin/sendmail systeme-si@dataone.fr

        echo "Fin du redémarrage des jboss" | tee -a /var/log/restart_jboss.log
        date >> /var/log/restart_jboss.log
        echo "" >> /var/log/restart_jboss.log
fi
