#!/bin/bash

#Définition des deux dossiers dans lesquels chercher une correspondance sur serv1
sssd="/etc/sssd/sssd.conf"
ssh="/etc/ssh/"

#Définition des variables permettant de vérifier si une correspondance a été trouvé dans les dossiers
grepsssd=$(grep serv1 "$sssd" | wc -l)
grepssh=$(grep serv1 "$ssh"* | wc -l)

#Si correspondance dans le fichier /etc/sssd/sssd.conf --> backup du fichier + changement + restart du service sssd
if [ "$grepsssd" != 0 ]; then
echo "Match found in "$sssd""
echo ""
cp -p "$sssd" /etc/sssd/sssd.conf-bck-`date +"%d-%m-%Y"` && echo "Backup of "$sssd" OK"
echo ""
sed -i 's/serv1/serv2/g' "$sssd" && echo "Changes OK"
echo ""
service sssd restart && echo "Service sssd restarted"
echo ""
else
echo "Nothing found in "$sssd""
echo ""
fi

#Si correspondance dans le dossier /etc/ssh, afficher les fichiers concernés. Changement à faire à la main + restart service ssh
if [ "$grepssh" != 0 ]; then
echo "Match found in "$ssh""
echo ""
grep serv1 "$ssh"*
else
echo "Nothing found in "$ssh""
fi
