#!/bin/bash

#Définition des deux dossiers dans lesquels chercher une correspondance sur serv1
sssd="/etc/sssd/sssd.conf"
ssh="/etc/ssh/*"

#Définition des variables permettant de vérifier si une correspondance a été trouvée dans les dossiers
grepsssd=$(grep serv1 "$sssd" | wc -l)
grepssh=$(grep serv1 "$ssh" | wc -l)

#Si correspondance dans le fichier /etc/sssd/sssd.conf --> backup du fichier + changement + restart du service sssd
if [ "$grepsssd" != 0 ]; then 
cp -p "$sssd" /etc/sssd/sssd.conf-bck-`date +"%d-%m-%Y"` && echo "copy ok" 
sed -i 's/serv1/serv2/g' "$sssd" && echo "sed ok"
service sssd restart && echo "service sssd restarted"
else
echo "Nothing found in "$sssd""
fi

#Si correspondance dans le dossier /etc/ssh, afficher les fichiers concernés. Changement à faire à la main + restart service ssh
if [ "$grepssh" != 0 ]; then 
grep gdpdc1 "$ssh"
else
echo "Nothing found in "$ssh""
fi
