#!/bin/bash

 

#Définition des variables récupérant le statut de chacune des instances PN (is running/is not running)

PN1=$(/etc/init.d/inspire-production-server-current1 status | grep not | wc -l)

PN2=$(/etc/init.d/inspire-production-server-current2 status | grep not | wc -l)

 

#Si PN1 est dans l'état "not running" ---> Relance du service + affichage du statut pour vérification

if [ "$PN1" = 1 ]; then

  echo "Instance 1 is not running"

  /etc/init.d/inspire-production-server-current1 start > /dev/null && echo "Instance 1 started"

  /etc/init.d/inspire-production-server-current1 status

  echo ""

else

  echo "Instance 1 is running"

  echo ""

fi

 

#Si PN2 est dans l'état "not running" ---> Relance du service + affichage du statut pour vérification

if [ "$PN2" = 1 ]; then

  echo "Instance 2 is not running"

  /etc/init.d/inspire-production-server-current2 start > /dev/null && echo "Instance 2 started"

  /etc/init.d/inspire-production-server-current2 status

else

  echo "Instance 2 is running"

fi

 

PN1=$(/etc/init.d/inspire-production-server-current1 status | grep not | wc -l)

PN2=$(/etc/init.d/inspire-production-server-current2 status | grep not | wc -l)

 

#Prévenance par mail avec le statut du redémarrage

if [ "$PN1" = "$PN2" ] && [ "$PN1" = 0 ]; then

  echo -e "Subject:Redemarrage des PN\n\nBonjour,\n\nLe PN "hostname" a redémarré avec succès.\n\nCordialement." | /usr/sbin/sendmail prod-info@dataone.fr

else

  echo -e "Subject:Erreur de redemarrage du PN\n\nBonjour,\n\nLe PN "hostname" a rencontré un soucis de redémarrage, merci de vérifier les services.\n\nCordialement." | /usr/sbin/sendmail prod-info@dataone.fr

fi
