#!/bin/bash

#Verify if var contains a specific substring
LOT="a"

while [ "$LOT" = "a" ]
do
        read -p "Veuillez saisir le nom du lot : " LOT
        SYMP=$(echo "$LOT" | grep SYMP-NUM)

if [ "$LOT" = "$SYMP" ]; then
        echo "Erreur, les lots SYMP-NUM sont renommés une fois arrivés sur la gateway. Veuillez utiliser le nom renommé"
        LOT="a"
fi
done

#Verify if var is equal to some specifics strings
TYPE="a"

while [ "$TYPE" = "a" ]
do
        read -p "darkone ou hubeone : " TYPE

if [ "$TYPE" != "darkone" ] && [ "$TYPE" != "hubeone" ]; then
        echo "Erreur, veuillez saisir hubeone ou darkone"
        TYPE="a"
fi
done
